### ISSUE TITLE
not compatible with rusherhack

### ISSUE THREAD

**Issue by Witherinqq** [olliem5/ferox#44]
when i open gui my game crashes :-|

**Comment by ProfKambing** [comment]
bind it to something else, this is due to rh gui being on the same key

**Comment by Manesko55** [comment]
> bind it to something else, this is due to rh gui being on the same key

that isn't the problem
rusher hack isn't compatible with it at all

**Comment by GentleWither** [comment]
yes bcuz i have rusherhack gui bounded at rshift
and i sniff coke

**Comment by Eonexe** [comment]
close? I think it was fixed.
