### ISSUE TITLE
chams crash the client with a null pointer when enabled

### ISSUE THREAD

**Issue by Gopro336** [olliem5/ferox#45]

**Comment by moomooooo** [comment]
CLEAN_FEROX_1.3-BUILDABLE-SRC

**Comment by ChiquitaV2** [comment]
Soon I hope I wanna run this client but I don’t trust “Ollie”

**Comment by olliem5** [comment]
yeah, i know about this bug, i might fix it if i get bored. i also broke vanilla chams somehow lol

**Comment by olliem5** [comment]
i don't trust that "ollie" kid either 🤒

**Comment by ChiquitaV2** [comment]
he seems like a bad egg if you ask me 🤫

**Comment by moomooooo** [comment]
look at these commits... what does "Update README.md" mean????? is that a rat????

**Comment by olliem5** [comment]
yes, i agree, he is well known for being a really mean person and not being nice to anybody

**Comment by olliem5** [comment]
the readme is the rat, how did you figure it out?

**Comment by moomooooo** [comment]
im really smart with computer stuff

**Comment by ChiquitaV2** [comment]
no, I think the rat is in the "mixins.ferox.json" but we should wait to see what the rat cleaner says

**Comment by olliem5** [comment]
make sure to run the client through theia to check all of the hidden rats in all of the modules, that's sure to pickup my webhook strings!

**Comment by ChiquitaV2** [comment]
will do thanks, I trust theia with everything it's never failed me

**Comment by GentleWither** [comment]
how 2 be retarded in a nutshell 
"ChiquitaV2"

**Comment by Manesko55** [comment]
> how 2 be retarded in a nutshell
> "ChiquitaV2"

🤦

**Comment by ChiquitaV2** [comment]
> how 2 be retarded in a nutshell
> "ChiquitaV2"

😭😭😭

**Comment by moomooooo** [comment]
> how 2 be retarded in a nutshell
> "ChiquitaV2"

chiquita weetawded
